feat: connected with backend to get daily puzzle
NicholasBottone/Wordify pull request #13
Opened 2022-05-11 03:33 UTC by andrew7li

connected with backend!

2022-05-11 20:18 UTC, jamesdupark requested changes

2022-05-11 20:18 UTC, jamesdupark commented on components/GameOver.tsx
> +          !correct && letter !== "" && correctWord!.includes(letter);
**fitness for purpose**: do you need to check whether the letter is the empty string here? Shouldn't you already have checked that the word is a valid 5-letter word?

2022-05-11 20:18 UTC, jamesdupark commented on components/GameOver.tsx
> +        return correct ? 2 : close ? 1 : 0;
**safety from bugs/ease of understanding**: In your comment on line 8, you detail that the letter should be mapped to `0` if correct, `1` if close, and `2` if wrong. However, what you are doing here is mapping it to `2` if correct and `0` if wrong. I don't know if this was accidental, intentional, or if you just forgot to change your comment, but you should make sure this is consistent!

2022-05-11 20:18 UTC, jamesdupark commented on components/GameOver.tsx
> +          !correct && letter !== "" && correctWord!.includes(letter);
**safety from bugs**: this system of word validation fails when there are repeated letters - if a letter that appears only once in the solution appears twice in a guess, both letters will be marked as either correct/close, even though only one should receive that designation. For example, if the solution is `bread` and I guess `steer`, the first `e` is marked green and the second is marked yellow, even though only the first should be marked green. To prevent this, I suggest reworking your validation algorithm to iterate through the solution word letter-by-letter and check the guess against the solution. This way, each marking on the guess corresponds directly to one letter in the solution.

2022-05-11 20:18 UTC, jamesdupark commented on pages/api/puzzle/daily/index.ts
> +          .send("Invalid resultBoard value in request body!");
very good change, highly necessary thank you.

2022-05-11 20:18 UTC, jamesdupark commented on pages/api/puzzle/daily/index.ts
> +  await User.updateOne(
**fitness for purpose**: is there a reason you added the `await`s here? I don't think it's strictly necessary (unless you found it being a problem as you used this endpoint?) since nothing that follows the update statements really depends upon the updates having completed

2022-05-13 07:20 UTC, NicholasBottone requested changes

2022-05-13 07:20 UTC, NicholasBottone commented on lib/wordVerifier/WordVerifier.tsx
> +import React from "react";
This file is not a React component and does not return any JSX, therefore React should not be imported, the file extension should not be .tsx, and the first letter of the filename should be lowercase.

2022-05-13 07:22 UTC, NicholasBottone requested changes

2022-05-13 07:22 UTC, NicholasBottone commented on pages/game.tsx
> +import GameOver, { SendResults } from "../components/GameOver";
It seems like this function does not exist, this is causing the build to fail.

2022-05-13 07:33 UTC, NicholasBottone approved these changes

2022-05-13 07:36 UTC, jamesdupark approved these changes

2022-05-13 07:37 UTC, merged